name: check-for-ps
on:
  schedule:
    - cron: "*/20 7-22 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://ghcr.io/gowerc/pschecker:latest
        env: 
            TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
            TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
            TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
            TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
