name: 'check'

on:
  schedule:
  - cron: "*/30 7-22 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04
    container:
      image: docker://ghcr.io/gowerc/pschecker:latest
    env: 
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
      TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
    steps:
    - uses: actions/checkout@v2
    - run: python3 pschecker.py
    - uses: actions/upload-artifact@v2
      with:
        name: logs
        path: log/*.html