name: check-for-ps
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/gowerc/pschecker:latest
    steps:
      - uses: actions/checkout@v2
      - run: python3.9 pschecker.py